### ISSUE TITLE
alt for decorative Images

### ISSUE THREAD

**Issue by nawfelsekrafi** [anoshaahmed/accessibility-info#1]
The info are great @anoshaahmed , just you can add this to alt attribute as mentioned in the MDN .

Images with no semantic meaning—such as those which are solely decorative—or of limited informational value, should have their alt attributes set to the empty string (""). This is shown in the example below.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images
![giphy_s](https://user-images.githubusercontent.com/48069841/151659054-98f0226d-6629-453b-be88-879454f256e4.gif)

**Comment by anoshaahmed** [comment]
thank u @nawfelsekrafi i added that. please feel free to let me know of more issues thanks!
